### PR TITLE
Rina files

### PR DESCRIPTION
**Pull request by rinatiwari**
@williamjones0706 @morrowzl  I have make some final changes in my table please merge since it didn't allow me now to merge.

### CODE REVIEW

**Comment by rinatiwari** [comment]
> _No description provided._

Can you merge this?

**Comment by morrowzl** [comment]
The conflicting files are the different versions of table.html in your branch and on the master branch.

The app is using data_table.html

Did you intend to make changes to data_table.html or replace it with table.html?

Or, if you staged both data_table.html and table.html, but only need the first, we can exclude the old file.

**Comment by rinatiwari** [comment]
> The conflicting files are the different versions of table.html in your branch and on the master branch.
> 
> The app is using data_table.html
> 
> Did you intend to make changes to data_table.html or replace it with table.html?
> 
> Or, if you staged both data_table.html and table.html, but only need the first, we can exclude the old file.

Actually@Will has framed or sourced table.html in data_table. Actually it need data_table too no replacement

**Comment by rinatiwari** [comment]
fixed it .

**Pull request closed without merging**
